apiVersion: v1
kind: Namespace
metadata:
  name: nginx-demo
  labels:
    kubernetes.io/metadata.name: nginx-demo
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-vol
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: infoscale-concat-sc
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginxsrv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxsrv
  template:
    metadata:
      labels:
        app: nginxsrv
    spec:
      initContainers:
        - name: init-web
          image: busybox:1.36
          command: ["sh","-c"]
          args:
            - |
              if [ ! -f /work/index.html ]; then
                echo "<h1>Hello from PVC - InfoScale RWX</h1>" > /work/index.html
              fi
          volumeMounts:
            - name: webdata
              mountPath: /work
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:1.27-alpine
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: webdata
              mountPath: /usr/share/nginx/html
          readinessProbe:
            httpGet:
              path: /
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 20
      volumes:
        - name: webdata
          persistentVolumeClaim:
            claimName: nginx-vol
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  type: ClusterIP
  selector:
    app: nginxsrv
  ports:
    - port: 80
      targetPort: 8080