apiVersion: v1
kind: Service
metadata:
  name: nginx-service
  namespace: nginx-demo
spec:
  selector:
    app: nginxsrv
  type: NodePort
  ports:
    - name: http
      protocol: TCP
      port: 80          # ???????? service ???????????????? cluster
      targetPort: 8080  # ?????????? container (nginx-unprivileged)
      nodePort: 31544        # ????????????????????? nodeIP:nodePort
