apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  namespace: nginx-demo
  labels:
    app: nginxsrv
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginxsrv
  template:
    metadata:
      labels:
        app: nginxsrv
    spec:
      securityContext:
        runAsNonRoot: true
        seccompProfile:
          type: RuntimeDefault

      # ?? Init container to ensure index.html exists
      initContainers:
        - name: init-web
          image: busybox:1.36
          command: ["sh", "-c"]
          args:
            - |
              set -eu
              dst=/usr/share/nginx/html/index.html
              if [ ! -s "$dst" ]; then
                echo '<!doctype html><title>Hello</title><h1>?? Welcome to NGINX</h1><p>Auto-created by initContainer</p>' > "$dst"
                echo "Created default index.html"
              else
                echo "index.html already exists — skipping"
              fi
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: webdata
              mountPath: /usr/share/nginx/html
              readOnly: false

      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:stable-alpine
          ports:
            - containerPort: 8080
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: ["ALL"]
          volumeMounts:
            - name: webdata
              mountPath: /usr/share/nginx/html
              readOnly: false
          readinessProbe:
            httpGet:
              path: /index.html
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 20
          livenessProbe:
            httpGet:
              path: /index.html
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 30
      volumes:
        - name: webdata
          persistentVolumeClaim:
            claimName: nginx-pvc
