apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nginx-vol
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: infoscale-concat-sc
  volumeMode: Filesystem
  resources:
    requests:
      storage: 5Gi