
---
apiVersion: v1
kind: Pod
metadata:
  name: redis
  labels:
    name: redis
spec:
  containers:
    - name: redis
      image: redis
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: "/mnt/arctera"
          name: vol1
  volumes:
    - name: vol1
      persistentVolumeClaim:
        claimName: csi-infoscale-pvc
