
---
apiVersion: v1
kind: Pod
metadata:
  name: test-pod
spec:
  containers:
    - name: test-pod-container
      image: busybox
      volumeMounts:
        - mountPath: "/ephemeral"
          name: ephemeral-volume
      command: [ "sleep", "1000000" ]
  volumes:
    - name: ephemeral-volume
      ephemeral:
        volumeClaimTemplate:
          metadata:
            labels:
              type: test-pod-volume
          spec:
            accessModes: [ "ReadWriteOnce" ]
            storageClassName: "csi-infoscale-sc"
            resources:
              requests:
                storage: 1Gi
