
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: csi-infoscale-performance-sc
  annotations:
    storageclass.kubernetes.io/is-default-class: "false"
provisioner: org.veritas.infoscale
reclaimPolicy: Delete
allowVolumeExpansion: true
parameters:
  fstype: vxfs

  # (optional) Specifies a volume layout type.
  # Supported layouts: stripe, mirror, stripe-mirror, mirror-stripe, concat, concat-mirror, mirror-concat
  layout: "stripe-mirror"

  # (optional) Specifies the number of disk or host failures a storage object can tolerate.
  faultTolerance: "1"

  # (optional) Specifies disks with the specified media type. All disks with the given mediatype are selected for volume creation.
  # Supported values: hdd, ssd
  mediaType: "ssd"
