
---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: infoscale-tools-cert
  namespace: infoscale-vtas
spec:
  commonName: infoscale-toolset
  usages:
  - client auth
  duration: 1h0m0s
  issuerRef:
    kind: ClusterIssuer
    name: infoscale-cert-issuer
  secretName: infoscale-tools-tls
---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: infoscale-rekey-schedule
  namespace: infoscale-vtas
spec:
  # Runs 09:00, on day 1 of the month"
  schedule: "0 9 1 * *"
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      backoffLimit: 6
      ttlSecondsAfterFinished: 300
      activeDeadlineSeconds: 300
      template:
        spec:
          serviceAccount: infoscale-sds-operator
          restartPolicy: Never
          containers:
          - name: infoscale-rekey-schedule
            image: <registry>/arctera/infoscale-sds-toolset:9.1.0-rhel
            imagePullPolicy: IfNotPresent
            command:
            - /infoscale-toolset
            args:
            - operation
            - rekey
            # will iterate all infoscale clusters if namespace is not specified
            - --certdir=$(INFOSCALE_AUTH_KEYSTORE)
            env:
              - name: ISO_DEPLOYMENT_NS
                valueFrom:
                  fieldRef:
                    fieldPath: metadata.namespace
              - name: INFOSCALE_AUTH_KEYSTORE
                value: "/etc/vx/toolset/"
            volumeMounts:
            - mountPath: /etc/vx/clusterset
              name: infoscale-clusterset
              readOnly: true
            - mountPath: /etc/vx/toolset
              name: cert
              readOnly: true
          volumes:
          - name: cert
            secret:
              defaultMode: 420
              secretName: infoscale-tools-tls
          - name: infoscale-clusterset
            configMap:
              name: infoscale-clusterset
              optional: true
