
---
apiVersion: v1
kind: Pod
metadata:
  name: csi-app
spec:
  containers:
    - name: app
      image: ubuntu
      command: ["/bin/sh"]
      args: ["-c", "while true; do sleep 100; done"]
      volumeMounts:
        - name: persistent-storage
          mountPath: /mnt
  volumes:
    - name: persistent-storage
      persistentVolumeClaim:
        claimName: csi-infoscale-pvc
