
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-infoscale-block-pvc
spec:
  volumeMode: Block
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: csi-infoscale-sc
