
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: infoscale-sds-operator-sub
  # Namespace should be either infoscale-vtas
  # or openshift-operators
  namespace: infoscale-vtas
spec:
  # Cluster admin can move to fast channel for cross release InfoScale upgrades
  channel: fast
  name: infoscale-sds-operator
  installPlanApproval: Manual
  # Source can be infoscale-sds-operator-catalog
  # if infoscale-catsrc.yaml is used
  source: certified-operators
  sourceNamespace: openshift-marketplace
  startingCSV: infoscale-sds-operator.v9.1.0
  # Use the following configuration to toggle custom values and the specified values are defaults
  #config:
  #  env:
  #  - name: EO_COMPLIANCE
  #    value: disabled
  #  - name: LOG_FILE_PERMISSION
  #    value: "600"
  #  - name: TLS_CIPHER_SUITES
  #    value: TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256,TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
  #  - name: REST_CLIENT_DEBUG
  #    value: "true"
  #  - name: KUBELET_PATH
  #    value: "/var/lib/kubelet"
